# Generated by Django 5.2.11 on 2026-03-15 14:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseSessionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("one_rep_max", models.DecimalField(decimal_places=2, max_digits=6)),
                ("session_load", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "target_load",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight_floor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "weight_ceiling",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["session__completed_at"],
            },
        ),
    ]
