# Generated by Django 5.2.11 on 2026-03-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisesessionsnapshot",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session_snapshots",
                to="exercises.exercise",
            ),
        ),
    ]
