# Generated by Django 5.2.11 on 2026-03-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0002_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisesessionsnapshot",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_snapshots",
                to="programs.program",
            ),
        ),
    ]
