# Generated by Django 5.2.11 on 2026-03-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0003_initial"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisesessionsnapshot",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_snapshots",
                to="workouts.workoutcompletionrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="exercisesessionsnapshot",
            index=models.Index(
                fields=["program", "exercise"], name="analytics_e_program_78835e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercisesessionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("program", "exercise", "session"),
                name="unique_snapshot_per_exercise_per_session",
            ),
        ),
    ]
