# Generated by Django 5.2.11 on 2026-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="client_avatars/"),
        ),
    ]
