class PlaneOfMotionVocabulary:
    SAGITTAL = "SAGITTAL"
    FRONTAL = "FRONTAL"
    TRANSVERSE = "TRANSVERSE"


class AnatomicalDirectionVocabulary:
    ANTERIOR = "ANTERIOR"
    POSTERIOR = "POSTERIOR"
    LATERAL = "LATERAL"
    MEDIAL = "MEDIAL"
    SUPERIOR = "SUPERIOR"
    INFERIOR = "INFERIOR"


class MovementPatternVocabulary:
    FLEXION = "FLEXION"
    EXTENSION = "EXTENSION"
    ABDUCTION = "ABDUCTION"
    ADDUCTION = "ADDUCTION"
    INTERNAL_ROTATION = "INTERNAL_ROTATION"
    EXTERNAL_ROTATION = "EXTERNAL_ROTATION"
    HORIZONTAL_ADDUCTION = "HORIZONTAL_ADDUCTION"
    HORIZONTAL_ABDUCTION = "HORIZONTAL_ABDUCTION"
    DORSIFLEXION = "DORSIFLEXION"
    PLANTARFLEXION = "PLANTARFLEXION"
    ELEVATION = "ELEVATION"
    DEPRESSION = "DEPRESSION"
    PROTRACTION = "PROTRACTION"
    RETRACTION = "RETRACTION"


class MuscleRoleVocabulary:
    AGONIST = "AGONIST"
    ANTAGONIST = "ANTAGONIST"
    SYNERGIST = "SYNERGIST"
    FIXATOR = "FIXATOR"


class JointVocabulary:
    SHOULDER = "SHOULDER"
    ELBOW = "ELBOW"
    SPINE = "SPINE"
    HIP = "HIP"
    KNEE = "KNEE"
    ANKLE = "ANKLE"
    SCAPULA = "SCAPULA"


class MuscleGroupVocabulary:
    CHEST = "CHEST"
    SHOULDER = "SHOULDER"
    TRICEPS = "TRICEPS"

    BACK = "BACK"
    BICEPS = "BICEPS"
    UPPER_ARM = "UPPER_ARM"
    LOWER_ARM = "LOWER_ARM"
    FOREARM = "FOREARM"

    CORE = "CORE"

    GLUTES = "GLUTES"
    QUADRICEPS = "QUADRICEPS"
    HAMSTRINGS = "HAMSTRINGS"
    CALVES = "CALVES"
    HIP_FLEXORS = "HIP_FLEXORS"
