class MembershipVocabulary:
    PENDING = "PENDING_TRAINER_REVIEW"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    DISSOLVED_BY_CLIENT = "DISSOLVED_BY_CLIENT"
    DISSOLVED_BY_TRAINER = "DISSOLVED_BY_TRAINER"

    ACTIVE_STATES = {PENDING, ACTIVE}

    INACTIVE_STATES = {REJECTED, DISSOLVED_BY_CLIENT, DISSOLVED_BY_TRAINER}
