# Generated by Django 5.2.11 on 2026-03-15 14:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Equipment",
            },
        ),
        migrations.CreateModel(
            name="ExerciseMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Exercise Movements",
                "ordering": ["phase__code"],
            },
        ),
        migrations.CreateModel(
            name="ExercisePhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Exercise Phases",
            },
        ),
        migrations.CreateModel(
            name="JointContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Joint Contributions",
                "ordering": ["-joint_range_of_motion__impact_factor"],
            },
        ),
        migrations.CreateModel(
            name="JointRangeOfMotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("impact_factor", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                "verbose_name_plural": "Joint Ranges of Motion",
                "ordering": ["-impact_factor"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exercise_name", models.CharField(max_length=100, unique=True)),
                ("api_name", models.CharField(max_length=100, unique=True)),
                ("instructions", models.TextField(blank=True)),
                ("safety_tips", models.TextField(blank=True)),
                ("is_enriched", models.BooleanField(default=False)),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="exercises.equipment"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Exercises",
                "ordering": ["exercise_name"],
            },
        ),
    ]
