# Generated by Django 5.2.11 on 2026-03-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biology", "0001_initial"),
        ("exercises", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="experience_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="users.experiencelevel",
            ),
        ),
        migrations.AddField(
            model_name="exercisemovement",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_movements",
                to="exercises.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercisemovement",
            name="phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_movements",
                to="exercises.exercisephase",
            ),
        ),
        migrations.AddField(
            model_name="jointcontribution",
            name="exercise_movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="joint_contributions",
                to="exercises.exercisemovement",
            ),
        ),
        migrations.AddField(
            model_name="jointcontribution",
            name="joint_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_contributions",
                to="biology.jointaction",
            ),
        ),
        migrations.AddField(
            model_name="jointcontribution",
            name="joint_range_of_motion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_contributions",
                to="exercises.jointrangeofmotion",
            ),
        ),
        migrations.AddConstraint(
            model_name="exercisemovement",
            constraint=models.UniqueConstraint(
                fields=("phase", "exercise"), name="unique_phase_per_exercise_movement"
            ),
        ),
        migrations.AddConstraint(
            model_name="jointcontribution",
            constraint=models.UniqueConstraint(
                fields=("exercise_movement", "joint_action"),
                name="unique_exercise_movement_per_joint_action",
            ),
        ),
    ]
