# Generated by Django 5.2.11 on 2026-03-13 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPhaseOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("default_duration_days", models.PositiveSmallIntegerField(default=28)),
            ],
            options={
                "verbose_name_plural": "Program Phase Options",
            },
        ),
        migrations.CreateModel(
            name="ProgramPhaseStatusOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Program Phase Status Options",
            },
        ),
        migrations.CreateModel(
            name="ProgramStatusOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Program Status Options",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_name", models.CharField(max_length=150)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, max_length=500)),
                ("completion_notes", models.TextField(blank=True, max_length=500)),
                ("abandonment_reason", models.CharField(blank=True, max_length=200)),
                (
                    "created_by_trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experience_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="users.experiencelevel",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer_client_membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="users.trainerclientmembership",
                    ),
                ),
                (
                    "training_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="users.traininggoal",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="programs.programstatusoption",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase_name", models.CharField(blank=True, max_length=120)),
                ("phase_goal", models.CharField(blank=True, max_length=200)),
                ("sequence_order", models.PositiveSmallIntegerField(default=1)),
                ("trainer_notes", models.TextField(blank=True, max_length=500)),
                ("client_notes", models.TextField(blank=True, max_length=500)),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_reason", models.CharField(blank=True, max_length=200)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("archived_reason", models.CharField(blank=True, max_length=200)),
                (
                    "created_by_trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_program_phases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_program_phases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="programs.program",
                    ),
                ),
                (
                    "phase_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phases",
                        to="programs.programphaseoption",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_phases",
                        to="programs.programphasestatusoption",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sequence_order", "program"),
                        name="unique_sequence_order_per_program",
                    )
                ],
            },
        ),
    ]
