# Generated by Django 5.2.11 on 2026-03-15 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnatomicalDirection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Anatomical Directions",
            },
        ),
        migrations.CreateModel(
            name="Joint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Joints",
            },
        ),
        migrations.CreateModel(
            name="MovementPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Movement Patterns",
            },
        ),
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Muscle Groups",
            },
        ),
        migrations.CreateModel(
            name="MuscleRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Muscle Roles",
            },
        ),
        migrations.CreateModel(
            name="PlaneOfMotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "Planes of Motion",
            },
        ),
        migrations.CreateModel(
            name="JointAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "joint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="biology.joint",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joint_actions",
                        to="biology.movementpattern",
                    ),
                ),
                (
                    "plane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joint_actions",
                        to="biology.planeofmotion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Joint Actions",
            },
        ),
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("order_index", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=300)),
                (
                    "anatomical_direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscles",
                        to="biology.anatomicaldirection",
                    ),
                ),
                (
                    "muscle_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscles",
                        to="biology.musclegroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Muscles",
            },
        ),
        migrations.CreateModel(
            name="MuscleInvolvement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("impact_factor", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "joint_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscles",
                        to="biology.jointaction",
                    ),
                ),
                (
                    "muscle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="biology.muscle",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscles",
                        to="biology.musclerole",
                    ),
                ),
            ],
            options={
                "ordering": ["-impact_factor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("muscle", "joint_action"),
                        name="unique_muscle_joint_action",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="jointaction",
            constraint=models.UniqueConstraint(
                fields=("joint", "movement"), name="unique_movement_per_joint"
            ),
        ),
    ]
