class ProgramStatusesVocabulary:
    CREATING = "CREATING"
    REVIEW = "OUT_FOR_REVIEW"
    READY = "READY_TO_BEGIN"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"

    ALL = {CREATING, REVIEW, READY, IN_PROGRESS, COMPLETED, ABANDONED}

    SUBMITTED_STATES = {REVIEW, READY, IN_PROGRESS, COMPLETED, ABANDONED}

    REVIEWED_STATES = {READY, IN_PROGRESS, COMPLETED, ABANDONED}

    STARTED_STATES = {IN_PROGRESS, COMPLETED, ABANDONED}

    LIVE_STATES = {CREATING, REVIEW, READY, IN_PROGRESS}

    FINISHED_STATES = {COMPLETED, ABANDONED}


class ProgramPhaseStatusesVocabulary:
    PLANNED = "PLANNED"
    NEXT = "NEXT"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    ARCHIVED = "ARCHIVED"

    ALL = {PLANNED, NEXT, ACTIVE, COMPLETED, SKIPPED, ARCHIVED}

    PRE_ACTIVE_STATES = {PLANNED, NEXT}

    ACTIONABLE_STATES = {NEXT, ACTIVE}

    LIVE_STATES = {PLANNED, NEXT, ACTIVE}

    FINISHED_STATES = {COMPLETED, SKIPPED, ARCHIVED}
