#!/bin/bash
# Usage: ./scripts/check
# Example: ./scripts/check

# Ensure the script stops on errors
set -e

# Run the command in the 'web' container and remove it after
docker-compose run --rm web python manage.py check
