#!/bin/bash
# Usage: ./scripts/enter-shell
# Example: ./scripts/enter-shell

# Ensure the script stops on errors
set -e

# Run the command in the 'web' container and remove it after
docker-compose run --rm web python manage.py shell
