#!/bin/bash
# Usage: ./scripts/migrate

echo "RUNNING MIGRATIONS..."
# Make migrations to database
docker-compose run --rm web python manage.py makemigrations
docker-compose run --rm web python manage.py migrate
