#!/bin/bash
# Usage: ./scripts/reset_db

echo "DESTROYING DATABASE..."
docker-compose down -v

echo "REBUILDING..."
docker-compose build web

echo "STARTING UP..."
docker-compose up -d

echo "WAITING FOR DB..."
sleep 3  # Give the DB a second to wake up

echo "RUNNING MIGRATIONS..."
# Make migrations to database
docker-compose run --rm web python manage.py makemigrations
docker-compose run --rm web python manage.py migrate

echo "SEEDING DATABASE"
docker-compose run --rm web python manage.py seed_db

echo "SEEDING DEMO ENVIRONMENT"
docker-compose run --rm web python manage.py seed_demo

echo "✅ DATABASE RESET COMPLETE."
