#!/bin/bash
# Usage: ./scripts/test_app [app_name]
# Example: ./scripts/test_app users

# Ensure the script stops on errors
set -e

# Run the command in the 'web' container and remove it after
docker-compose run --rm web pytest "apps/$@"
