#!/bin/bash
# Usage: ./scripts/test_all
# Example: ./scripts/test_all

# Ensure the script stops on errors
set -e

# Run the command in the 'web' container and remove it after
docker-compose run --rm web pytest --create-db
