# Generated by Django 5.2.11 on 2026-02-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutsetcompletionrecord",
            old_name="workout_in_progress_record",
            new_name="exercise_completion_record",
        ),
        migrations.AddField(
            model_name="workoutexercisecompletionrecord",
            name="workout_completion_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_records",
                to="workouts.workoutcompletionrecord",
            ),
        ),
    ]
