# Generated by Django 5.2.11 on 2026-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workouts",
            "0002_rename_workout_in_progress_record_workoutsetcompletionrecord_exercise_completion_record_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsetcompletionrecord",
            name="is_skipped",
            field=models.BooleanField(default=False),
        ),
    ]
