# Generated by Django 5.2.11 on 2026-02-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workouts",
            "0004_alter_workoutexercisecompletionrecord_workout_exercise_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutcompletionrecord",
            name="workout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_record",
                to="workouts.workout",
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercisecompletionrecord",
            name="workout_exercise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_record",
                to="workouts.workoutexercise",
            ),
        ),
        migrations.AlterField(
            model_name="workoutsetcompletionrecord",
            name="workout_set",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_record",
                to="workouts.workoutset",
            ),
        ),
    ]
