# Generated by Django 5.2.11 on 2026-02-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_alter_workoutcompletionrecord_workout_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={"ordering": ["scheduled_for"]},
        ),
        migrations.AlterModelOptions(
            name="workoutcompletionrecord",
            options={"ordering": ["completed_at"]},
        ),
        migrations.AlterModelOptions(
            name="workoutexercise",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="workoutexercisecompletionrecord",
            options={"ordering": ["completed_at"]},
        ),
        migrations.AlterModelOptions(
            name="workoutset",
            options={"ordering": ["set_order"]},
        ),
        migrations.AlterModelOptions(
            name="workoutsetcompletionrecord",
            options={"ordering": ["completed_at"]},
        ),
        migrations.AlterField(
            model_name="workoutexercisecompletionrecord",
            name="workout_completion_record",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_records",
                to="workouts.workoutcompletionrecord",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="workoutexercise",
            unique_together={("workout", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="workoutset",
            unique_together={("workout_exercise", "set_order")},
        ),
    ]
