# Generated by Django 5.2.11 on 2026-02-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_alter_workout_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexercisecompletionrecord",
            name="workout_completion_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_records",
                to="workouts.workoutcompletionrecord",
            ),
        ),
    ]
