# Generated by Django 5.2.11 on 2026-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_trainerclientmembership_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerclientmembership",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
