#!/bin/bash
# Usage: ./scripts/backend/manage [command_name]

# Ensure the script stops on errors
set -e

cd "$(dirname "$0")/../.."

# Run the command in the 'web' container and remove it after
docker-compose run --rm web python manage.py "$@"
