#!/bin/bash
# Usage: ./scripts/backend/migrate

# Ensure the script stops on errors
set -e

cd "$(dirname "$0")/../.."

echo "SHUTTING DOWN CONTAINERS"
docker compose down -v

echo "SPINNING BACK UP"
docker compose up -d

echo "RUNNING MIGRATIONS..."
# Make migrations to database
docker-compose run --rm web python manage.py makemigrations
docker-compose run --rm web python manage.py migrate
