#!/bin/bash
# Usage: ./scripts/backend/show-urls

# Ensure the script stops on errors
set -e

cd "$(dirname "$0")/../.."

# Spin up the container, print urls and remove it
docker-compose run --rm web sh -c "python manage.py show_urls > /app/urls.txt"
