#!/bin/bash
# Usage: ./scripts/backend/test-all

# Ensure the script stops on errors
set -e

cd "$(dirname "$0")/../.."

# Run the command in the 'web' container and remove it after
docker-compose run --rm web pytest --create-db
