# Generated by Django 5.2.11 on 2026-02-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programphase",
            options={"ordering": ["-phase_option__order_index"]},
        ),
        migrations.AlterUniqueTogether(
            name="programphase",
            unique_together={("program", "phase_option")},
        ),
    ]
