# Generated by Django 5.2.11 on 2026-02-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_alter_programphase_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="trainer_goal",
            new_name="training_goal",
        ),
    ]
